### ISSUE TITLE
Join Media Queries after update to v1.12

### ISSUE THREAD

**Issue by goeko** [KKBOX/FireApp#179]
After update to v1.12 my used script to join media queries output error.

Here the functional Script for my stuff until v1.11:
https://gist.github.com/StanAngeloff/3164569#file-join-media-queries-php

Here the error output from FireApp:

<pre>
Warning: preg_replace(): Compilation failed: regular expression is too large at offset 41497 in /www/_git/redmine/PATH/sass/_scripts/join-media-queries.php on line 84
</pre>

How can I fix it?
Is it a bug or a feature? :-)
